# Generated by Django 5.0 on 2024-01-13 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_tweet_comments_alter_tweet_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='insta_link',
            field=models.URLField(blank=True, null=True, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='profile',
            name='youtube_link',
            field=models.URLField(blank=True, null=True, verbose_name='Youtube'),
        ),
    ]
