# Generated by Django 5.0 on 2024-01-27 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_profile_insta_link_profile_youtube_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='comments',
        ),
        migrations.AlterField(
            model_name='comment',
            name='tweet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main.tweet'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='Про користувача'),
        ),
    ]
